config/routes.rb
Project4::Application.routes.draw do

  devise_for :users

  

  resources :task_user_proj_rels, only: [:new, :edit, :create, :destroy]
  match '/to-do', to: 'user_project_rels#todo'
  
  resources :projects do
    resources :tasks  do
      post 'comment'
      post 'tag'
    end
    resources :bugs do
      post 'comment'
      post 'tag'
    end
    resources :resources  do
      post 'comment'
      post 'tag'
    end

    resources :users, :controller => "user_project_rels" 

    member do
      post 'comment'
      post 'tag'
    end
  end
  
  root :to => 'projects#index'

  match '/feed' => 'projects#feed',
      as: :feed,
      defaults: { format: 'rss' }

end

app/models/task.rb
# == Schema Information
#
# Table name: task_bugs
#
#  id                   :integer          not null, primary key
#  title                :string(255)
#  status               :string(255)
#  priority             :string(255)
#  due_date             :date
#  estimated_date       :date
#  percentage_completed :float
#  task_or_bug          :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Task < ActiveRecord::Base
  set_table_name "task_bugs"
  
  has_many :task_user_proj_rels, :foreign_key => "task_bug_id",:dependent => :destroy
  has_many :user_project_rels, :through => :task_user_proj_rels
  has_many :users, :through => :user_project_rels
  has_many :project, :through => :user_project_rels
  
  attr_accessible :due_date, :estimated_date, :percentage_completed, :priority, :status, :task_or_bug, :title, :owner
  
  validates :title, :status, :priority, :due_date, :presence=> true
   validates :percentage_completed, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100}
  validates :title, :length => { :maximum => 250 }
  validates :status, :inclusion => { :in => ['Open', 'In Progress', 'Complete'],
    :message => "%{value} is not a valid status" }    
  validates :priority, :inclusion => { :in => %w(High Medium Low),
    :message => "%{value} is not a valid status" }
    
  acts_as_commentable
  acts_as_taggable

  before_save :default_for_task
  def default_for_task
    self.task_or_bug = 'T'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def tag
    task = Task.find(params[:task_id])
    task.tag_list.concat(params[:tag].split(","))
    task.save
    redirect_to project_task_path(params[:project_id], task)
  end
  
  def comment
    comment = Comment.build_from(Task.find(params[:task_id]), 
                                 current_user, 
                                 params[:comment][:body])
    comment.save
    redirect_to project_task_path(params[:project_id], params[:task_id])
  end

  # GET /tasks
  # GET /tasks.json
  def index
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    @comment = Comment.new
    @tag = String.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @is_admin = UserProjectRel.find_by_user_id_and_project_id(current_user.id,params[:project_id]).role == "Administrator"
     @task = Task.new
     @project = Project.find(params[:project_id])
#     @is_admin = UserProjectRel.find_by_user_id_and_project_id(current_user.id,params[:project_id]).role == "Administrator"
    respond_to do |format|
      format.html # new.html.erb
      format.mobile # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @is_admin = UserProjectRel.find_by_user_id_and_project_id(current_user.id,params[:project_id]).role == "Administrator"
    @task = Task.find(params[:id])
     @project = Project.find(params[:project_id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @is_admin = UserProjectRel.find_by_user_id_and_project_id(current_user.id,params[:project_id]).role == "Administrator"
    @rel=UserProjectRel.find_by_user_id_and_project_id(params[:task][:task_or_bug],params[:project_id])
    @task = @rel.tasks.create(params[:task])
    @project = Project.find(params[:project_id])
    
    respond_to do |format|
      if @rel.save
        format.html { redirect_to project_path(params[:project_id]), notice: 'Task was successfully created.' }
        format.mobile { redirect_to project_path(params[:project_id]), notice: 'Task was successfully created.' }
        format.json { render json: @bug, status: :created, location: @bug }
      else
        format.html { render action: "new" }
        format.mobile { render action: "new" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @is_admin = UserProjectRel.find_by_user_id_and_project_id(current_user.id,params[:project_id]).role == "Administrator"
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to project_path(params[:project_id]), notice: 'Task was successfully updated.' }
        format.mobile { redirect_to project_path(params[:project_id]), notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.mobile { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_path(params[:project_id]) }
      format.mobile { redirect_to project_path(params[:project_id]) }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %> 
  </div>
 <% if @is_admin %> 
   <div class="field">
    <%= f.label :assigned_to %><br />
  	<%= f.collection_select :task_or_bug, @project.users, :id, :username %>
  <% end %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, ["Select","Open","In Progress","Complete"] %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select :priority, ["Select","High","Medium","Low"] %>
  </div>
  <div class="field">
    <%= f.label :percentage_completed %><br />
    <%= f.text_field :percentage_completed %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :estimated_date %><br />
    <%= f.date_select :estimated_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_form.mobile.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %> 
  </div>
 <% if @is_admin %> 
   <div class="field">
    <%= f.label :assigned_to %><br />
  	<%= f.collection_select :task_or_bug, @project.users, :id, :username %>
  <% end %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, ["Select","Open","In Progress","Complete"] %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select :priority, ["Select","High","Medium","Low"] %>
  </div>
  <div class="field">
    <%= f.label :percentage_completed %><br />
    <%= f.text_field :percentage_completed %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :estimated_date %><br />
    <%= f.date_select :estimated_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit Task: <%= @task.title %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>|<%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,@task] %>

app/views/tasks/edit.mobile.erb
<h2>Edit Task: <%= @task.title %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>|<%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,@task] %>

app/views/tasks/index.html.erb
<% role = Project.find(params[:project_id]).user_project_rels.find_by_user_id(current_user).role %>
<% @project = Project.find(params[:project_id]) %>
<h3 align="center"><u>Tasks</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Status</th>
    <th scope="col">Priority</th>
    <th></th>
    <th></th>
  </tr>

<% @pagination=@project.tasks.paginate(:page => params[:page], :per_page => 10).each do |task| %>
  <tr>
    <td scope="row"><%= task.title %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,task] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_task_path(@project,task) %></td>
    <% else %>
    <td/>
    <%end%>
    <% if role=="Administrator" %>
    <td><%= link_to  image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,task] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @pagination %>
<br />
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Task', new_project_task_path(@project) %>
<% end %>

app/views/tasks/index.mobile.erb
<% role = Project.find(params[:project_id]).user_project_rels.find_by_user_id(current_user).role %>
<% @project = Project.find(params[:project_id]) %>
<h3 align="center"><u>Tasks</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Status</th>
    <th scope="col">Priority</th>
    <th></th>
    <th></th>
  </tr>

<% @pagination=@project.tasks.paginate(:page => params[:page], :per_page => 10).each do |task| %>
  <tr>
    <td scope="row"><%= task.title %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,task] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_task_path(@project,task) %></td>
    <% else %>
    <td/>
    <%end%>
    <% if role=="Administrator" %>
    <td><%= link_to  image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,task] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @pagination %>
<br />
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Task', new_project_task_path(@project) %>
<% end %>

app/views/tasks/new.html.erb
<h2>Add a new Task to <%= @project.name %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>

app/views/tasks/new.mobile.erb
<h2>Add a new Task to <%= @project.name %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h2>View Task: <%= @task.title %></h2>
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>|<%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_task_path(@project,@task) %>
<p>
  <b>Task:</b>
  <%= @task.title %>
</p>

<p>
  <b>Assigned to:</b>
  <% @task.users.each do |user| %>
  <%= user.username %>
  <%end%>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Percentage completed:</b>
  <%= @task.percentage_completed %>
</p>

<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>

<p>
  <b>Estimated date:</b>
  <%= @task.estimated_date %>
</p>

<%= render 'layouts/tag_comment', thingy: @task, url: project_task_comment_path(@project, @task), tag_url: project_task_tag_path(@project, @task) %>

app/views/tasks/show.mobile.erb
<p id="notice"><%= notice %></p>
<h2>View Task: <%= @task.title %></h2>
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>|<%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_task_path(@project,@task) %>
<p>
  <b>Task:</b>
  <%= @task.title %>
</p>

<p>
  <b>Assigned to:</b>
  <% @task.users.each do |user| %>
  <%= user.username %>
  <%end%>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Percentage completed:</b>
  <%= @task.percentage_completed %>
</p>

<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>

<p>
  <b>Estimated date:</b>
  <%= @task.estimated_date %>
</p>


<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>|<%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_task_path(@project,@task) %>

<%= render 'layouts/tag_comment', thingy: @task, url: project_task_comment_path(@project, @task), tag_url: project_task_tag_path(@project, @task) %>