config/routes.rb
Project4::Application.routes.draw do

  devise_for :users

  

  resources :task_user_proj_rels, only: [:new, :edit, :create, :destroy]
  match '/to-do', to: 'user_project_rels#todo'
  
  resources :projects do
    resources :tasks  do
      post 'comment'
      post 'tag'
    end
    resources :bugs do
      post 'comment'
      post 'tag'
    end
    resources :resources  do
      post 'comment'
      post 'tag'
    end

    resources :users, :controller => "user_project_rels" 

    member do
      post 'comment'
      post 'tag'
    end
  end
  
  root :to => 'projects#index'

  match '/feed' => 'projects#feed',
      as: :feed,
      defaults: { format: 'rss' }

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, presence: true
  validates :description, presence: true

  has_many :users,:through => :user_project_rels
  has_many :user_project_rels,:dependent => :destroy
  has_many :task_user_proj_rels,:through => :user_project_rels
  has_many :tasks, :through => :task_user_proj_rels
  has_many :bugs, :through => :task_user_proj_rels
  has_many :resources,:through => :project_resource_rels
  has_many :project_resource_rels,:dependent => :destroy

  acts_as_commentable
  acts_as_taggable # gives us a project.tag_list
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!, except: :feed

  def tag
    project = Project.find(params[:id])
    project.tag_list.concat(params[:tag].split(","))
    project.save
    redirect_to project_path(project)
  end

  def comment
    comment = Comment.build_from(Project.find(params[:id]), 
                                 current_user, 
                                 params[:comment][:body])
    comment.save
    redirect_to project_path(params[:id])
  end

  def feed
    @projects = current_user.projects

    respond_to do |format|
      format.rss { render layout: false }
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.mobile # index.html.erb
      format.json { render json: @projects }
      format.rss { render layout: false }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @isAdmin = @project.user_project_rels.find_by_user_id(current_user).role== "Administrator" 
    @comment = Comment.new
    @tag = String.new
    respond_to do |format|
      format.html # show.html.erb
      format.mobile # show.html.erb
      format.json { render json: @project }
    end
  end
  

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.mobile # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
          @rel=@project.user_project_rels.build(:project_id=>@project.id, :user_id=>current_user.id, :role=>'Administrator')
          @rel.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.mobile { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.mobile { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to projects_url , notice: 'Project was successfully updated.' }
        format.mobile { redirect_to projects_url , notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.mobile { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url } 
      format.mobile { redirect_to projects_url }  
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_form.mobile.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h2>Editing <%=@project.name%></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), projects_path %>|<%= link_to image_tag("show.png", :border=>0, :class => 'icon'), @project %> 

app/views/projects/edit.mobile.erb
<h2>Editing <%=@project.name%></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), projects_path %>|<%= link_to image_tag("show.png", :border=>0, :class => 'icon'), @project %> 

app/views/projects/index.html.erb
<h1>Welcome!</h1>
<h2 align="left"> Your current projects </h2>
<div id="container">
<table id="tab">
<thead>
  <tr>
     <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Role</th>
</tr>
</thead>
<tbody>
<% current_user.projects.each do |project| %>
  <tr>
    <td scope="row"><%= link_to project.name, project %></td>
    <td scope="row" width="480px"><%= project.description %></td>
    <td scope="row"><%= project.user_project_rels.find_by_user_id(current_user).role %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), project %></td>
    <% if project.user_project_rels.find_by_user_id(current_user).role== "Administrator" %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_path(project) %></td>
    <td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/><td/>
    <% end %>
<% end %>
</tbody>
</table>

<br />
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/index.mobile.erb
<h1>Welcome!</h1>
<h2 align="left"> Your current projects </h2>
<div id="container">
<table id="tab">
<thead>
  <tr>
     <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Role</th>
</tr>
</thead>
<tbody>
<% current_user.projects.each do |project| %>
  <tr>
    <td scope="row"><%= link_to project.name, project %></td>
    <td scope="row" width="480px"><%= project.description %></td>
    <td scope="row"><%= project.user_project_rels.find_by_user_id(current_user).role %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), project %></td>
    <% if project.user_project_rels.find_by_user_id(current_user).role== "Administrator" %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_path(project) %></td>
    <td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/><td/>
    <% end %>
<% end %>
</tbody>
</table>

<br />
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), projects_path %>

app/views/projects/new.mobile.erb
<h1>New Project</h1>

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), projects_path %>

app/views/projects/show.html.erb
<br/>
<h2> Summary of <%= @project.name %></h2>
<%= role = @project.user_project_rels.find_by_user_id(current_user).role %>
<p id="notice"><%= notice %></p>
</p>
<div>
<p> 
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), projects_path %>
</p>
</div>
<div id="page-container">
<div id="other-left">
<h3 align="center"><u>Tasks</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Status</th>
    <th scope="col">Priority</th>
    <th></th>
    <th></th>
  </tr>

<% @project.tasks.limit(10).each do |task| %>
  <tr>
    <td scope="row"><%= link_to task.title, [@project,task] %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,task] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_task_path(@project,task) %></td>
    <% else %>
    <td/>
    <%end%>
    <% if role=="Administrator" %>
    <td><%= link_to  image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,task] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<br />
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Task', new_project_task_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_tasks_path(@project) %>
</div>

<div id="other-right">
<h3 align="center"><u>Bugs</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Status</th>
    <th scope="col">Priority</th>
    <th></th>
    <th></th>
  </tr>

<% @project.bugs.limit(10).each do |bug| %>
  <tr>
    <td scope="row"><%= link_to bug.title, [@project,bug] %></td>
    <td><%= bug.status %></td>
    <td><%= bug.priority %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,bug] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_bug_path(@project,bug) %></td>
    <% else %>
    <td/>
    <%end%>
    <% if role=="Administrator" %>
    <td><%= link_to  image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,bug], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<br/>
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Bug', new_project_bug_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_bugs_path(@project) %>
</div>
</div>

<div id="page-container">
<div id="other-left">
<h3 align="center"><u>Resources</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th></th>
    <th></th>
  </tr>
<% @project.resources.limit(5).each do |resource| %>
  <tr>
    <td scope="col"><%= link_to resource.title, [@project,resource] %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,resource] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'),  edit_project_resource_path(@project,resource) %></td>
    <td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,resource], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<br/>
<% if !(role=="Client") %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Resource', new_project_resource_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_resources_path(@project) %>
</div>

<div id="other-right">
<h3 align="center"><u>Users</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">User</th>
    <th scope="col">Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project.user_project_rels.limit(5).each do |user_project_rel| %>
  <tr>
    <td><%= user_project_rel.username %></td>
    <td><%= user_project_rel.role %></td>
    <% if role=="Administrator" %>
    	<td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), project_user_path(@project,user_project_rel), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'Add User', new_project_user_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_users_path(@project) %>
</div>
</div>
<%= render "layouts/tag_comment", thingy: @project, url: comment_project_path, tag_url: tag_project_path(@project) %>

app/views/projects/show.mobile.erb
<br/>
<h2> Summary of <%= @project.name %></h2>
<%= role = @project.user_project_rels.find_by_user_id(current_user).role %>
<p id="notice"><%= notice %></p>
</p>
<div>
<p> 
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), projects_path %>
</p>
</div>
<div id="page-container">
<div id="other-left">
<h3 align="center"><u>Tasks</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Status</th>
    <th scope="col">Priority</th>
    <th></th>
    <th></th>
  </tr>

<% @project.tasks.limit(10).each do |task| %>
  <tr>
    <td scope="row"><%= link_to task.title, [@project,task] %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,task] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_task_path(@project,task) %></td>
    <% else %>
    <td/>
    <%end%>
    <% if role=="Administrator" %>
    <td><%= link_to  image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,task] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<br />
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Task', new_project_task_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_tasks_path(@project) %>
</div>

<div id="other-right">
<h3 align="center"><u>Bugs</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Status</th>
    <th scope="col">Priority</th>
    <th></th>
    <th></th>
  </tr>

<% @project.bugs.limit(10).each do |bug| %>
  <tr>
    <td scope="row"><%= link_to bug.title, [@project,bug] %></td>
    <td><%= bug.status %></td>
    <td><%= bug.priority %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,bug] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_bug_path(@project,bug) %></td>
    <% else %>
    <td/>
    <%end%>
    <% if role=="Administrator" %>
    <td><%= link_to  image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,bug], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<br/>
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Bug', new_project_bug_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_bugs_path(@project) %>
</div>
</div>

<div id="page-container">
<div id="other-left">
<h3 align="center"><u>Resources</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th></th>
    <th></th>
  </tr>
<% @project.resources.limit(5).each do |resource| %>
  <tr>
    <td scope="col"><%= link_to resource.title, [@project,resource] %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,resource] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'),  edit_project_resource_path(@project,resource) %></td>
    <td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,resource], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<br/>
<% if !(role=="Client") %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Resource', new_project_resource_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_resources_path(@project) %>
</div>

<div id="other-right">
<h3 align="center"><u>Users</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">User</th>
    <th scope="col">Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project.user_project_rels.limit(5).each do |user_project_rel| %>
  <tr>
    <td><%= user_project_rel.username %></td>
    <td><%= user_project_rel.role %></td>
    <% if role=="Administrator" %>
    	<td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), project_user_path(@project,user_project_rel), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'Add User', new_project_user_path(@project) %>
<% end %>
 | <%= link_to 'More ...', project_users_path(@project) %>
</div>
</div>
<%= render "layouts/tag_comment", thingy: @project, url: comment_project_path, tag_url: tag_project_path(@project) %>