config/routes.rb
Project4::Application.routes.draw do

  devise_for :users

  

  resources :task_user_proj_rels, only: [:new, :edit, :create, :destroy]
  match '/to-do', to: 'user_project_rels#todo'
  
  resources :projects do
    resources :tasks  do
      post 'comment'
      post 'tag'
    end
    resources :bugs do
      post 'comment'
      post 'tag'
    end
    resources :resources  do
      post 'comment'
      post 'tag'
    end

    resources :users, :controller => "user_project_rels" 

    member do
      post 'comment'
      post 'tag'
    end
  end
  
  root :to => 'projects#index'

  match '/feed' => 'projects#feed',
      as: :feed,
      defaults: { format: 'rss' }

end

app/views/resources/_form.html.erb
<%= form_for(([@project, @resource]), :html => {:multipart => true} ) do |f| %> 
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Supporting Link" %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label "Upload document" %><br />
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_form.mobile.erb
<%= form_for(([@project, @resource]), :html => {:multipart => true} ) do |f| %> 
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Supporting Link" %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label "Upload document" %><br />
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>|<%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,@resource] %> 

app/views/resources/edit.mobile.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>|<%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,@resource] %> 

app/views/resources/index.html.erb
<% role = Project.find(params[:project_id]).user_project_rels.find_by_user_id(current_user).role %>
<% @project = Project.find(params[:project_id]) %>
<h3 align="center"><u>Resources</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th></th>
    <th></th>
  </tr>
<% @pagination=@project.resources.paginate(:page => params[:page], :per_page => 10).each do |resource| %>
  <tr>
    <td scope="col"><%= resource.title %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,resource] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'),  edit_project_resource_path(@project,resource) %></td>
    <td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,resource], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @pagination %>
<br/>
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |
<% if !(role=="Client") %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Resource', new_project_resource_path(@project) %>
<% end %>

app/views/resources/index.mobile.erb
<% role = Project.find(params[:project_id]).user_project_rels.find_by_user_id(current_user).role %>
<% @project = Project.find(params[:project_id]) %>
<h3 align="center"><u>Resources</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">Title</th>
    <th></th>
    <th></th>
  </tr>
<% @pagination=@project.resources.paginate(:page => params[:page], :per_page => 10).each do |resource| %>
  <tr>
    <td scope="col"><%= resource.title %></td>
    <td><%= link_to image_tag("show.png", :border=>0, :class => 'icon'), [@project,resource] %></td>
    <% if !(role=="Client") %>
    <td><%= link_to image_tag("edit.png", :border=>0, :class => 'icon'),  edit_project_resource_path(@project,resource) %></td>
    <td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), [@project,resource], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @pagination %>
<br/>
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |
<% if !(role=="Client") %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'New Resource', new_project_resource_path(@project) %>
<% end %>

app/views/resources/new.html.erb
<h2>Add a new Resource to <%= @project.name %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>

app/views/resources/new.mobile.erb
<h2>Add a new Resource to <%= @project.name %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>
<h2>View Resource: <%= @resource.title %></h2>
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |<%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_resource_path(@project,@resource)  %> 
<p>
  <b>Title:</b>
  <%= @resource.title %>
</p>

<p>
  <b>Content:</b>
  <%= @resource.content %>
</p>

<% if !@resource.attachment_file_size.nil? %>
<p>
  <b>Document:</b>
  <%= link_to @resource.attachment_file_name, @resource.attachment.url(:original, false) %>
</p>
<%end%>

<%= render 'layouts/tag_comment', thingy: @resource, url: project_resource_comment_path(@project, @resource), tag_url: project_resource_tag_path(@project, @resource) %>

app/views/resources/show.mobile.erb
<p id="notice"><%= notice %></p>
<h2>View Resource: <%= @resource.title %></h2>
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |<%= link_to image_tag("edit.png", :border=>0, :class => 'icon'), edit_project_resource_path(@project,@resource)  %> 
<p>
  <b>Title:</b>
  <%= @resource.title %>
</p>

<p>
  <b>Content:</b>
  <%= @resource.content %>
</p>

<% if !@resource.attachment_file_size.nil? %>
<p>
  <b>Document:</b>
  <%= link_to @resource.attachment_file_name, @resource.attachment.url(:original, false) %>
</p>
<%end%>

<%= render 'layouts/tag_comment', thingy: @resource, url: project_resource_comment_path(@project, @resource), tag_url: project_resource_tag_path(@project, @resource) %>