config/routes.rb
Project4::Application.routes.draw do

  devise_for :users

  

  resources :task_user_proj_rels, only: [:new, :edit, :create, :destroy]
  match '/to-do', to: 'user_project_rels#todo'
  
  resources :projects do
    resources :tasks  do
      post 'comment'
      post 'tag'
    end
    resources :bugs do
      post 'comment'
      post 'tag'
    end
    resources :resources  do
      post 'comment'
      post 'tag'
    end

    resources :users, :controller => "user_project_rels" 

    member do
      post 'comment'
      post 'tag'
    end
  end
  
  root :to => 'projects#index'

  match '/feed' => 'projects#feed',
      as: :feed,
      defaults: { format: 'rss' }

end

app/models/user_project_rel.rb
# == Schema Information
#
# Table name: user_project_rels
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  project_id :integer
#  role       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UserProjectRel < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  has_many :task_user_proj_rels,:dependent => :destroy
  has_many :tasks, :through => :task_user_proj_rels
  has_many :bugs, :through => :task_user_proj_rels

  attr_accessible :role, :user_id, :project_id, inclusion: { :in => %w(Administrator Developer Tester Client) }
    
    def username()
      User.find(user_id).username
    end
    
end

app/controllers/user_project_rels_controller.rb
class UserProjectRelsController < ApplicationController
  
  
  # GET /to-do
  # GET /to-do.json
  def todo
    respond_to do |format|
      format.html # show.html.erb
      format.mobile # show.html.erb
      format.json { render json: @project }
    end
  end
  
  # GET /user_project_rels
  # GET /user_project_rels.json
  def index
    @user_project_rels = UserProjectRel.all

    respond_to do |format|
      format.html # index.html.erb
      format.mobile # index.html.erb
      format.json { render json: @user_project_rels }
    end
  end

  # GET /user_project_rels/1
  # GET /user_project_rels/1.json
  def show
    u = UserProjectRel.find(params[:id]).user
    
    @projects = u.projects

    #@sample = UserProjectRel.find(params[:id]).task_user_proj_rels

    respond_to do |format|
      format.html # show.html.erb
      format.mobile # show.html.erb
      format.json { render json: @user_project_rel }
    end
  end

  # GET /user_project_rels/new
  # GET /user_project_rels/new.json
  def new
    @project = Project.find(params[:project_id])
    @user_project_rel = UserProjectRel.new
    @user_list = User.where("id NOT IN (?)",@project.users.map)

    respond_to do |format|
      format.html # new.html.erb
      format.mobile # new.html.erb
      format.json { render json: @user_project_rel }
    end
  end

  # GET /user_project_rels/1/edit
  def edit
        @project = Project.find(params[:project_id])
    @user_project_rel = UserProjectRel.find(params[:id])
  end

  # POST /user_project_rels
  # POST /user_project_rels.json
  def create
    @project = Project.find(params[:project_id])
    params[:user_project_rel][:project_id]=params[:project_id]
    @user_project_rel = UserProjectRel.new(params[:user_project_rel])

    respond_to do |format|
      if @user_project_rel.save
        format.html { redirect_to @project, notice: 'User was successfully added.' }
        format.mobile { redirect_to @project, notice: 'User was successfully added.' }
        format.json { render json: @user_project_rel, status: :created, location: @user_project_rel }
      else
        format.html { render action: "new" }
        format.mobile { render action: "new" }
        format.json { render json: @user_project_rel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_project_rels/1
  # PUT /user_project_rels/1.json
  def update
        @project = Project.find(params[:project_id])
    @user_project_rel = UserProjectRel.find(params[:id])

    respond_to do |format|
      if @user_project_rel.update_attributes(params[:user_project_rel])
        format.html { redirect_to @project, notice: 'User project rel was successfully updated.' }
        format.mobile { redirect_to @project, notice: 'User project rel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.mobile { render action: "edit" }
        format.json { render json: @user_project_rel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_project_rels/1
  # DELETE /user_project_rels/1.json
  def destroy
        @project = Project.find(params[:project_id])
    @user_project_rel = UserProjectRel.find(params[:id])
    @user_project_rel.destroy

    respond_to do |format|
      format.html { redirect_to @project }
      format.mobile { redirect_to @project }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_project_rels_helper.rb
module UserProjectRelsHelper
end

app/views/user_project_rels/_form.html.erb
<%if @user_list.nil? || @user_list.size==0	 %>
<p id="notice">
 All the users are already added in the current project </p>
<%else %>
<%= form_for(@user_project_rel, :url => (@user_project_rel.persisted? ? project_user_path(@project, @user_project_rel) : project_users_path(@project))) do |f| %>
  <% if @user_project_rel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_project_rel.errors.count, "error") %> prohibited this User from being added:</h2>

      <ul>
      <% @user_project_rel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, @user_list , :id, :username %>
  </div>
    <div class="field">
    <%= f.label :role %><br />
    <%= f.select :role, %w(Administrator Developer Tester Client) %>
  </div>
  <div class="actions">
    <%= f.submit 'Add User' %>
  </div>
<% end %>
<%end%>

app/views/user_project_rels/_form.mobile.erb
<%if @user_list.nil? || @user_list.size==0	 %>
<p id="notice">
 All the users are already added in the current project </p>
<%else %>
<%= form_for(@user_project_rel, :url => (@user_project_rel.persisted? ? project_user_path(@project, @user_project_rel) : project_users_path(@project))) do |f| %>
  <% if @user_project_rel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_project_rel.errors.count, "error") %> prohibited this User from being added:</h2>

      <ul>
      <% @user_project_rel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, @user_list , :id, :username %>
  </div>
    <div class="field">
    <%= f.label :role %><br />
    <%= f.select :role, %w(Administrator Developer Tester Client) %>
  </div>
  <div class="actions">
    <%= f.submit 'Add User' %>
  </div>
<% end %>
<%end%>

app/views/user_project_rels/edit.html.erb
<h1>Editing user_project_rel</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_project_rel %> |
<%= link_to 'Back', user_project_rels_path %>

app/views/user_project_rels/edit.mobile.erb
<h1>Editing user_project_rel</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_project_rel %> |
<%= link_to 'Back', user_project_rels_path %>

app/views/user_project_rels/index.html.erb
<% role = Project.find(params[:project_id]).user_project_rels.find_by_user_id(current_user).role %>
<% @project = Project.find(params[:project_id]) %>

<h3 align="center"><u>Users</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">User</th>
    <th scope="col">Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pagination=@project.user_project_rels.paginate(:page => params[:page], :per_page => 10).each do |user_project_rel| %>
  <tr>
    <td><%= user_project_rel.username %></td>
    <td><%= user_project_rel.role %></td>
    <% if role=="Administrator" %>
    	<td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), project_user_path(@project,user_project_rel), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @pagination %>
<br />
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'Add User', new_project_user_path(@project) %>
<% end %>

app/views/user_project_rels/index.mobile.erb
<% role = Project.find(params[:project_id]).user_project_rels.find_by_user_id(current_user).role %>
<% @project = Project.find(params[:project_id]) %>

<h3 align="center"><u>Users</u></h3>
<table id="hor-minimalist">
  <tr>
    <th scope="col">User</th>
    <th scope="col">Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pagination=@project.user_project_rels.paginate(:page => params[:page], :per_page => 10).each do |user_project_rel| %>
  <tr>
    <td><%= user_project_rel.username %></td>
    <td><%= user_project_rel.role %></td>
    <% if role=="Administrator" %>
    	<td><%= link_to image_tag("delete.jpeg", :border=>0, :height => '20px', :width=>'20px'), project_user_path(@project,user_project_rel), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <td/>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @pagination %>
<br />
<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %> |
<% if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to 'Add User', new_project_user_path(@project) %>
<% end %>

app/views/user_project_rels/new.html.erb
<h2>Add User to <%= @project.name %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>

app/views/user_project_rels/new.mobile.erb
<h2>Add User to <%= @project.name %></h2>

<%= render 'form' %>

<%= link_to image_tag("prev.png", :border=>0, :class => 'icon'), project_path(@project) %>

app/views/user_project_rels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_project_rel.user %>
</p>

<p>
  <b>Project:</b>
  <%= @user_project_rel.project %>
</p>

<p>
  <b>Role:</b>
  <%= @user_project_rel.role %>
</p>


<%= link_to 'Edit', edit_user_project_rel_path(@user_project_rel) %> |
<%= link_to 'Back', user_project_rels_path %>

app/views/user_project_rels/show.mobile.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_project_rel.user %>
</p>

<p>
  <b>Project:</b>
  <%= @user_project_rel.project %>
</p>

<p>
  <b>Role:</b>
  <%= @user_project_rel.role %>
</p>


<%= link_to 'Edit', edit_user_project_rel_path(@user_project_rel) %> |
<%= link_to 'Back', user_project_rels_path %>

app/views/user_project_rels/todo.html.erb
<% current_user.projects.each do |project| %>

<h2>
  <%= link_to project.name, "projects/#{project.id}"  %>  
  (<%= role = project.user_project_rels.find_by_user_id(current_user).role %>)
</h2>

<h3>Tasks</h3>

<table id="todo">
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Percentage completed</th>
    <th>Due date</th>
    <th>Estimated date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% project.tasks.where("user_project_rels.role='"+role+"'").order('task_bugs.priority').each do |task| %>
  <tr>
  	<td><%= link_to task.title, [project,task] %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= task.percentage_completed %></td>
    <td><%= task.due_date %></td>
    <td><%= task.estimated_date %></td>
  </tr>
<% end %>
</table>

<br />
<%if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to   'New Task', new_project_task_path(project) %>
<%end%>
<p> <br/>
</p>
<h3>Bugs</h3>

<table class="todo">
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Percentage completed</th>
    <th>Due date</th>
    <th>Estimated date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% project.bugs.where("user_project_rels.role='"+role+"'").order('task_bugs.priority').each do |bug| %>
  <tr>
  	<td><%= link_to bug.title, [project, bug] %></td>
    <td><%= bug.status %></td>
    <td><%= bug.priority %></td>
    <td><%= bug.percentage_completed %></td>
    <td><%= bug.due_date %></td>
    <td><%= bug.estimated_date %></td>
  </tr>
<% end %>
</table>
<br />
<%if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to   'New Bug', new_project_bug_path(project) %>
<%end%>

<% end %>
</table>

<br />

app/views/user_project_rels/todo.mobile.erb
<% current_user.projects.each do |project| %>

<h2>
  <%= link_to project.name, "projects/#{project.id}"  %>  
  (<%= role = project.user_project_rels.find_by_user_id(current_user).role %>)
</h2>

<h3>Tasks</h3>

<table id="todo">
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Percentage completed</th>
    <th>Due date</th>
    <th>Estimated date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% project.tasks.where("user_project_rels.role='"+role+"'").each do |task| %>
  <tr>
  	<td><%= link_to task.title, [project,task] %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= task.percentage_completed %></td>
    <td><%= task.due_date %></td>
    <td><%= task.estimated_date %></td>
  </tr>
<% end %>
</table>

<br />
<%if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to   'New Task', new_project_task_path(project) %>
<%end%>
<p> <br/>
</p>
<h3>Bugs</h3>

<table class="todo">
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Percentage completed</th>
    <th>Due date</th>
    <th>Estimated date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% project.bugs.where("user_project_rels.role='"+role+"'").each do |bug| %>
  <tr>
  	<td><%= link_to bug.title, [project, bug] %></td>
    <td><%= bug.status %></td>
    <td><%= bug.priority %></td>
    <td><%= bug.percentage_completed %></td>
    <td><%= bug.due_date %></td>
    <td><%= bug.estimated_date %></td>
  </tr>
<% end %>
</table>
<br />
<%if role=="Administrator" %>
<%=image_tag("add.jpeg", :height=>"10px", :width=>"10px")%>
<%= link_to   'New Bug', new_project_bug_path(project) %>
<%end%>

<% end %>
</table>

<br />